# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 518be73b605a73eae0074976feb00610b2b7a6d4118065d876af2dddf086f7232b6733df0507d8c68749e2813475b862cb59a8da763a5fba2f568d653940489e

test:
  secret_key_base: 00e541071254bb10abfddfccbc1ba15fa5b44c669c040c676bf397af51091f3204f21543763557630b7b2d72de31da589cfb158c5ffb80e79b74f910e5cfc1f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
